@startuml componentDiagram
package "User" {
  [Pepper]
  [Datenerhebungstool]
}

package "Server" {
  [Backend] <--> [AI Trainingstool]
  [Pepper] <--> [Backend]
  [Datenerhebungstool] <--> [Backend]

  database "Postgres DB"
}

[AI Trainingstool] <-- [Postgres DB]
[Backend] <-left-> [Postgres DB]
@enduml
