= Sprint Plan / Review

== Tasks

[%autowidth.stretch]
|===
|Name | Planned for this Sprint | Task Status | Planned for next Sprint
|Fabian Baitura

|
ðŸ“ Find out a way to make the face look less uncanny +
ðŸ“ Fill out docs
|
âœ”ï¸ Find out a way to make the face look less uncanny +
âœ”ï¸ Fill out docs
|
ðŸŽ¯ Implement new Face animations & algorithm (only the most important animations)
|Jonas Pamminger
|
ðŸ“ Face detection ServerSide with EmguCV
|
âœ”ï¸ Face detection ServerSide with EmguCV
|
ðŸŽ¯ Improvement of Question Management in the Configtool (Questions can be predefined for the assistant) +
ðŸŽ¯ Query Engineering
|Paul Nell
|
ðŸ“ Face Recognition +
|
âœ”ï¸ Face Recognition +
âœ”ï¸ Frontend Settings (In the Backend)
|
ðŸŽ¯ Not included Questions +
ðŸŽ¯ Frontend Session (In the Backend)
|Leon Leeb
|
ðŸ“ Face Follows User +
ðŸ“ Face speaks when spoken to +
ðŸ“ Make assistants visible in the config tool + Settings +
|
âœ”ï¸ Face Follows User +
âœ”ï¸ Face speaks when spoken to +
âœ”ï¸ Make assistants visible in the config tool + Settings
|
ðŸŽ¯ Frontend Login +
ðŸŽ¯ Settings in the config tool for each assistant

|Felix Dorn-Fussenegger
|
ðŸ“ Fix Speech to Text
|
âœ”ï¸ Fix Speech to Text
|
ðŸŽ¯ Fix Text to Speech -> Better and more natural voice

|===

=== Faced Obstacles or Challenges which occurred during this Sprint
* Dorn: x
* Nell: x
* Pamminger: x
* Baitura: x
* Leeb: Face has a bug when it comes to speaking

=== Schedule for the review meeting, including time slots for presentations, discussions, and feedback

Total review meeting duration: 20 minutes, comprising: +
- Presentations: 10 minutes +
- Discussions: 10 minutes +
